title: Mysterie's blog
description: IT Security stuff
author: Mysterie
github: https://github.com/mysterie
about: IT Security researcher, bug hunter, code breaker
disqus_shortname:
google_analytics: UA-7839874-4
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/Myst3rie"
    - icon: fa-github
      link: "https://github.com/Mysterie/"

share:
  twitter_username: Myst3rie

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://mysterie.github.io"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
